// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.TodoList = (function(superClass) {
    extend(TodoList, superClass);

    function TodoList() {
      return TodoList.__super__.constructor.apply(this, arguments);
    }

    TodoList.prototype.model = TodoItem;

    TodoList.prototype.initialize = function() {
      return console.log('todoList initialized');
    };

    TodoList.prototype.completed = function() {
      return this.where({
        completed: true
      });
    };

    TodoList.prototype.remaining = function() {
      return this.where({
        completed: false
      });
    };

    return TodoList;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=TodoList.js.map
