// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.AppView = (function(superClass) {
    extend(AppView, superClass);

    function AppView() {
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.el = $('#todoapp');

    AppView.prototype.initialize = function() {
      console.log('AppView initialized');
      this.input = this.$('#new-todo');
      this.todoList = this.model.get('todoList');
      return this.render();
    };

    AppView.prototype.render = function() {
      return this.$el.append(new TodoListView({
        collection: this.todoList
      }).$el);
    };

    AppView.prototype.events = {
      'keypress #new-todo': 'createOnEnter'
    };

    AppView.prototype.createOnEnter = function(e) {
      if (e.keyCode !== 13) {
        return;
      }
      if (!this.input.val()) {
        return;
      }
      this.todoList.add({
        description: this.input.val()
      });
      console.log(this.todoList);
      return this.input.val('');
    };

    return AppView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=AppView.js.map
