// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.TodoListView = (function(superClass) {
    extend(TodoListView, superClass);

    function TodoListView() {
      return TodoListView.__super__.constructor.apply(this, arguments);
    }

    TodoListView.prototype.tagName = 'ul';

    TodoListView.prototype.initialize = function() {
      this.collection.on('add remove change', (function(_this) {
        return function() {
          return _this.render();
        };
      })(this));
      return this.render();
    };

    TodoListView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.append(this.collection.map(function(todo) {
        return new TodoItemView({
          model: todo
        }).$el;
      }));
      return this;
    };

    return TodoListView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=TodoListView.js.map
